### ISSUE TITLE
UI overlap when switching between keyboards with and without predictive text

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client-mobile#116]
"If you switch the keyboard to a language (for example Finnish) that doesn't have the word suggestions appearing on top of the keyboard and then switch back to a language (for example English) that has the word suggestions... Those suggestions now overlap the Back and Send buttons. Also there is sometimes a white gap between a Finnish keyboard and the Back and Send buttons. Swiping up and down fixes it."

Was able to reproduce.

**Comment by anri-asaturov** [comment]
Fixed
