### ISSUE TITLE
Cursor disappears when navigating away from text entry

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client-mobile#130]
1. Enter a message thread.
2. Tap on the input area and type something. The cursor should appear as you type.
3. Tap on some previous message. Keyboard goes away.
4. Tap again on the input area and type something. Now the cursor does not appear anymore.

Does not prevent text entry. If you tap-hold and bring up magnifying glass, cursor returns.

**Comment by anri-asaturov** [comment]
Won't fix, this is WKWebView issue, we have no control over it
