### ISSUE TITLE
File downloads on Sailfish

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client-mobile#141]
Reported from Sailfish alpha tester:

Description: Sailfish OS doesn't have Android home screen by default, so there's no user interface to locate a downloaded file except via the app itself, leaving Sailfish OS terminal or some file browser app the only options for user. Also, while using any Android app for accessing files, another suitable Android app would be needed to open the file (depending on the file type). If no suitable app is pre-installed, Alien Dalvik (Android layer on Jolla) reports "Alert: No suitable applications found for this file type"

bug 1: Peerio doesn't have access to Sailfish OS apps to open files directly in those
bug 2: Downloaded files can't be located within Sailfish UI, and there's no Android UI
bug 3: File name remains in encrypted form after download (file itself is decrypted). This made it difficult to locate the file using for example "find" in terminal (yep, Jolla is equipped with Linux terminal app by default in developer mode)

Reproduce: Download any file on Peerio. Tap "Open". If another suitable Android app is not manually pre-installed, file can't be opened. Later, it can't be accessed in any easy way.

Suggested fix: Download files using their correct name directly to correct Sailfish OS home folders (depending on the suffix). Android apps don't have access to all Sailfish OS folders, but "home/nemo/" should be generally quite accessible. "home/nemo/Downloads" is a general folder for any file types, but it's not user friendly to save everything there, as pics should  goes to "home/nemo/Pictures", docs should go to "home/nemo/Documents" etc. for the best access

App version: 0.8.0

More: On my test, file was downloaded to "home/nemo/android_storage/Android/data/com.peerio/reviewjolla/decrypted/.....docx". I manually moved the file to correct folder "home/nemo/Documents" for the easiest access for this file type and managed to open it with Sailfish app "Documents" as it should be opened with.

**Comment by anri-asaturov** [comment]
We can't support android apps for Sailfish. When we are ready to make a native Sailfish cordova build - this issue won't be relevant.
