### ISSUE TITLE
Swipe gestures

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client-mobile#143]
Swipe to go back should be changed from right-to-left to left-to right. This command is more intuitive with the idea of a book, where you push to the right to go back and to left to go forward.

Swipe right-to-left can serve as 'forward' or an action command where relevant, e.g. send message

**Comment by anri-asaturov** [comment]
Currently navigation swipe is disabled, we need to rethink gestures globally
