### ISSUE TITLE
Pull out menus on Sailfish OS

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client-mobile#145]
"About pull-out-sidebars: Saifish apps don't use those at all, as swipe-from-side both on left and right are reserved for system UI. Sailfish apps have pull-out-topbar, and when necessary, pull-out-bottombar.

On Android apps running on Sailfish, sidebars can be accessed, but it requires the user to hold one finger on screen while pulling. Not all users even know it works like this.

Because of this, I'm suggesting that you add some visual guidance to show that there's a sidebar available, and additional guidance for first time use how it's accessed (on-screen-tip: hold + swipe-from-side)"

**Comment by anri-asaturov** [comment]
When we get to design a sailfish-compliant version let's do it centralised, not much sense in making just one thing 'the right way'.
