### ISSUE TITLE
Button to view conversation participants in thread view

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client-mobile#150]
User requested: A button to quickly view participants of a conversation in thread view. Button would expand drop down with list of all users in conversation. Only display if two or more participants. Might consider squeezing two names into thread titles and only display button for 3+ participants.

**Comment by anri-asaturov** [comment]
long tap or tap and hold could open 'quick look' kinda window/modal to show conversation info

**Comment by anri-asaturov** [comment]
https://github.com/PeerioTechnologies/peerio-client-mobile/issues/129 duplicate
