### ISSUE TITLE
possibility to search by username not indicated

### ISSUE THREAD

**Issue by ebilg** [PeerioTechnologies/peerio-client-mobile#220]
It would be useful if the search field text was changed to add username since it is possible to search by username as well as email/phone and if we remove required email/phone there will be no other way to add contacts. 
![img_9941](https://cloud.githubusercontent.com/assets/15635727/11002517/39f37ff8-847b-11e5-83fd-da1735a75420.PNG)

**Comment by anri-asaturov** [comment]
fixed
