### ISSUE TITLE
App locking

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client-mobile#79]
Using the lock icon to lock the app with passphrase/passcode or perhaps pattern screen. Idea is to not logout of account, allow for notifications, but prevent someone from snooping your phone and allow for quick login with passcode/pattern.

**Comment by anri-asaturov** [comment]
Offline login feature solves this. 'Sign out' instead of 'lock' and login will be as fast as theoretical 'unlock' we could implement.
